library(plumber)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(logger)

# Configure logger
log_threshold(DEBUG)

#* @apiTitle Space Weather R Backend
#* @apiDescription R-powered API for statistical analysis and visualization of NASA DONKI data.

#* Get statistical summary of NASA data
#* @post /analyze
#* @param data:json The raw JSON data from NASA DONKI
#* @param eventType:string The type of event (FLR, CME, etc.)
function(req) {
  log_info("Received analysis request")
  
  tryCatch({
    data <- fromJSON(req$postBody)
    
    if (length(data) == 0) {
      return(list(error = "Empty data provided"))
    }
    
    # Flatten and clean data
    df <- as.data.frame(data)
    
    # Example: Summarize numeric fields
    numeric_cols <- sapply(df, is.numeric)
    summary_stats <- if (any(numeric_cols)) {
      df %>%
        select(where(is.numeric)) %>%
        summarise(across(everything(), list(
          min = ~min(.x, na.rm = TRUE),
          max = ~max(.x, na.rm = TRUE),
          mean = ~mean(.x, na.rm = TRUE)
        )))
    } else {
      list(info = "No numeric columns found for analysis")
    }
    
    list(
      rowCount = nrow(df),
      summary = summary_stats,
      columns = names(df)
    )
  }, error = function(e) {
    log_error("Error in /analyze: {e$message}")
    list(error = e$message)
  })
}

#* Generate a distribution chart for NASA events
#* @get /chart
#* @serializer png
function(type = "CME") {
  log_info("Generating chart for type: {type}")
  
  # Simulated data for demonstration
  # In a real scenario, you would fetch or pass the data here
  set.seed(123)
  df <- data.frame(
    speed = rnorm(100, mean = 500, sd = 200),
    intensity = runif(100, 1, 10)
  )
  
  p <- ggplot(df, aes(x = speed)) +
    geom_histogram(fill = "#69b3a2", color = "#e9ecef", bins = 30) +
    theme_minimal() +
    labs(
      title = paste("Distribution of", type, "Speeds"),
      subtitle = "Generated by R Plumber Backend",
      x = "Speed (km/s)",
      y = "Frequency"
    )
  
  print(p)
}

#* Fetch live data from NASA DONKI
#* @get /fetch-nasa
#* @param type:string The event type (FLR, CME, etc.)
function(type = "FLR") {
  apiKey <- Sys.getenv("NASA_API_KEY", "DEMO_KEY")
  url <- paste0("https://api.nasa.gov/DONKI/", type, "?api_key=", apiKey)
  
  log_info("Fetching NASA data for: {type}")
  
  tryCatch({
    res <- readLines(url, warn = FALSE)
    data <- fromJSON(res)
    return(data)
  }, error = function(e) {
    log_error("Failed to fetch NASA data: {e$message}")
    list(error = "Failed to fetch from NASA")
  })
}

#* Health check
#* @get /health
function() {
  list(status = "R Backend is operational", timestamp = Sys.time())
}
