type User @table {
  authId: String!
  displayName: String
  email: String
}

type CMEAnalysis {
  time21_5: Timestamp
  latitude: Float
  longitude: Float
  halfAngle: Float
  speed: Int
  type: String
  isMostAccurate: Boolean
  note: String
}

type CME @table {
  activityID: String!
  startTime: Timestamp!
  note: String
  catalog: String
  sourceLocation: String
  cmeAnalyses: [CMEAnalysis]
}

type CachedData @table {
  endpoint: String!
  timestamp: Timestamp!
  data: String!
  ttl: Int
}